name: food_api_app
description: Application to display recipes from the FoodAPI.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.17.12
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
